config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: redirect('blog_posts')

  get 'blog_posts', to: 'blog_posts#index', as: 'blog_posts'
  post 'blog_posts', to: 'blog_posts#create'
  get 'blog_posts/new', to: 'blog_posts#new', as: 'new_blog_post'
  get 'blog_posts/:id', to: 'blog_posts#show', as: 'blog_post'
  get 'blog_posts/:id/edit', to: 'blog_posts#edit', as: 'edit_blog_post'
  patch 'blog_posts/:id', to: 'blog_posts#update'
  delete 'blog_posts/:id', to: 'blog_posts#destroy'

  get 'profile/:id', to: 'profile#show', as: 'profile'
  get 'profile/:id/edit', to: 'profile#edit', as: 'edit_profile'
  patch 'profile/:id', to: 'profile#update'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
# == Schema Information
#
# Table name: blog_posts
#
#  id         :bigint           not null, primary key
#  body       :text
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint
#
# Indexes
#
#  index_blog_posts_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class BlogPost < ApplicationRecord

  belongs_to(
	:creator,
	class_name:  'User',
	foreign_key: 'user_id',
	inverse_of:  :blog_posts
)

  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  about_me               :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  attr_accessor :about_me

  has_many(
	:blog_posts,
	class_name: 'BlogPost',
	foreign_key: 'user_id',
	inverse_of: :creator
)

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :require_permission, except: [:destroy, :edit, :index, :show, :new, :create]

  def index
    @blog_posts = BlogPost.order(created_at: :desc)
    render :index
  end

  def show
    @blog_post = BlogPost.find(params[:id])
    render :show
  end

  def new
    @blog_post = BlogPost.new
    render :new
  end

  def create
    @blog_post = current_user.blog_posts.build(params.require(:blog_post).permit(:title, :body))
    if @blog_post.save
      flash[:success] = 'Blog post was successfully created.'
      redirect_to blog_post_path(@blog_post)
    else
      flash.now[:error] = 'Unable to create blog post.'
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @blog_post = BlogPost.find(params[:id])

    unless current_user == @blog_post.creator
      redirect_to root_path, alert: "Access denied."
    end
    # render :edit
  end

  def update
    @blog_post = BlogPost.find(params[:id])
    if @blog_post.update(params.require(:blog_post).permit(:title, :body))
      flash[:success] = 'Blog post was successfully updated.'
      redirect_to blog_post_path(@blog_post)
    else
      flash.now[:error] = 'Unable to update blog post.'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @blog_post = BlogPost.find(params[:id])
    @blog_post.destroy
    flash[:success] = 'Blog post was successfully destroyed.'
    redirect_to blog_posts_url
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]
  before_action :set_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    render :show
  end

  def edit
    @user = User.find(params[:id])
    unless current_user == @user
      redirect_to root_path, alert: "Access denied."
    end
  end

  def update
    @user = User.find(params[:id])

    unless current_user == @user
      redirect_to root_path, alert: "Access denied."
    end

    if @user.update(params.require(:user).permit(:bio))
      redirect_to profile_path(@user), notice: "Profile updated successfully."
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end


end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  BOOTSTRAP_ALERT_CLASS = {
    'success' => 'alert-success',
    'error'   => 'alert-danger',
    'notice'  => 'alert-info',
    'alert'   => 'alert-danger',
    'warn'    => 'alert-warning'
  }.freeze

  def active_class(path)
    if request.path == path
      return 'active'
    else
      return ''
    end
  end

  def alert_class(flash_key)
    BOOTSTRAP_ALERT_CLASS.fetch(flash_key, 'alert-info')
  end

end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/blog_posts/edit.html.erb
<h1 class="my-4">Editing Blog Post</h1>

<%= bootstrap_form_with model: @blog_post, url: blog_post_path(@blog_post), method: :patch, data: { turbo: false } do |form| %>
  <%= form.text_field :title %>
  <%= form.text_area :body, rows: 16 %>
  <%= form.submit class: 'btn btn-primary my-3' %>
<% end %>

<p>
  <%= link_to 'Back', blog_posts_path, class: 'btn btn-outline-primary' %>
</p>

app/views/blog_posts/index.html.erb
<h1 class="my-4">Latest Blog Posts</h1>

<div class="table-responsive">
  <table class="table table-striped table-hover">

    <tbody>
      <% @blog_posts.each do |blog_post| %>
        <tr>
          <td><%= blog_post.title %></td>
          <td><%= blog_post.creator.email %></td>
          <td class="text-nowrap">
            <%= link_to 'Read', blog_post_path(blog_post), class: 'btn btn-primary btn-sm' %>
            <% if blog_post.creator == current_user %>
              <%= link_to 'Edit', edit_blog_post_path(blog_post), class: 'btn btn-primary btn-sm' %>
              <%= button_to 'Delete', blog_post_path(blog_post), method: :delete, data: { turbo: false }, class: 'btn btn-primary btn-sm', form: { class: 'd-inline' } %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>

  </table>
</div>

<p>
  <%= link_to 'New Blog Post', new_blog_post_path, class: 'btn btn-primary my-3' %>
</p>

app/views/blog_posts/new.html.erb
<h1 class="my-4">New Blog Post</h1>

<%= bootstrap_form_with model: @blog_post, url: blog_posts_path, method: :post, data: { turbo: false } do |form| %>
  <%= form.text_field :title %>
  <%= form.text_area :body, rows: 16 %>
  <%= form.submit class: 'btn btn-primary my-3' %>
<% end %>

<p>
  <%= link_to 'Back', blog_posts_path, class: 'btn btn-outline-primary' %>
</p>

app/views/blog_posts/show.html.erb
<h1 class="my-4"><%= @blog_post.title %></h1>

<%= simple_format(@blog_post.body) %>

<p>Created by: <%= @blog_post.creator.email %>
<p><%= link_to "Creator Profile", profile_path(@blog_post.creator) %></p>

<p class="mt-4">
  <%= link_to 'Back', blog_posts_path, class: 'btn btn-outline-primary' %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PracticeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
    
        <a class="navbar-brand" href="#">Blog</a>
    
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    
        <div class="collapse navbar-collapse"
            id="navbarSupportedContent">
    
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <%= link_to 'Home', blog_posts_path,
                          class: "nav-link #{active_class(blog_posts_path)}" %>
            </li>
          </ul>
    
          <ul class="navbar-nav">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to "Hi, #{current_user.email}", edit_user_registration_path,
                            class: "nav-link #{active_class(edit_user_registration_path)}" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Sign Out', destroy_user_session_path,
                            method: :delete, class: "nav-link" %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to 'Sign In', new_user_session_path,
                            class: "nav-link #{active_class(new_user_session_path)}" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Sign Up', new_user_registration_path,
                            class: "nav-link #{active_class(new_user_registration_path)}" %>
              </li>
            <% end %>
          </ul>
    
        </div>
    
      </div>
    </nav>


    <%= render 'shared/flash' %>

    <main role="main" class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <div class="alert <%= alert_class(key) %> alert-dismissible fade show" role="alert">
    <div class="text-center alert-message"><%= message %></div>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>